// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function SlackAuthSuccess(url: string): $CancellablePromise<void> {
    return $Call.ByID(3780080582, url);
}

export function StartLogin(): $CancellablePromise<void> {
    return $Call.ByID(1018092362);
}
