// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shared$0 from "./shared/models.js";

export function Boot(): $CancellablePromise<void> {
    return $Call.ByID(380504861);
}

export function GetChannels(teamID: string): $CancellablePromise<shared$0.Channel[]> {
    return $Call.ByID(3213025799, teamID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetIMs(teamID: string): $CancellablePromise<shared$0.Im[]> {
    return $Call.ByID(2667984826, teamID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetMessages(teamID: string, channelID: string, cursor: string): $CancellablePromise<shared$0.MessagesResponse | null> {
    return $Call.ByID(1012973511, teamID, channelID, cursor).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetUserProfile(teamID: string, userID: string, hash: string, size: number): $CancellablePromise<string> {
    return $Call.ByID(4097267401, teamID, userID, hash, size);
}

export function ResolveUsers(teamID: string, userIDs: string[]): $CancellablePromise<shared$0.UserProfile[]> {
    return $Call.ByID(2167812529, teamID, userIDs).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = shared$0.Channel.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = shared$0.Im.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = shared$0.MessagesResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = shared$0.UserProfile.createFrom;
const $$createType7 = $Create.Array($$createType6);
