// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as shared$0 from "./shared/models.js";

export function GetSession(): $CancellablePromise<shared$0.SlackSession | null> {
    return $Call.ByID(2427801811).then(($result: any) => {
        return $$createType1($result);
    });
}

export function IsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(1564912142);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(1310661145);
}

export function MaximiseWindow(): $CancellablePromise<void> {
    return $Call.ByID(1499305380);
}

export function SlackAuthSuccess(appUrl: string): $CancellablePromise<void> {
    return $Call.ByID(3780080582, appUrl);
}

export function StartLogin(): $CancellablePromise<void> {
    return $Call.ByID(1018092362);
}

// Private type creation functions
const $$createType0 = shared$0.SlackSession.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
