// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Channel {
    "id": string;
    "name": string;
    "is_channel": boolean;
    "is_group": boolean;
    "is_im": boolean;
    "is_mpim": boolean;
    "is_private": boolean;
    "created": number;
    "is_archived": boolean;
    "updated": number;
    "creator": string;
    "topic": {"value": string, "creator": string, "last_set": number};
    "purpose": {"value": string, "creator": string, "last_set": number};

    /**
     * properties
     */
    "properties": {"tabs": Tab[], "posting_restricted_to": {"type": string[], "user": string[]} | null};
    "previous_names"?: string[];

    /** Creates a new Channel instance. */
    constructor($$source: Partial<Channel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_channel" in $$source)) {
            this["is_channel"] = false;
        }
        if (!("is_group" in $$source)) {
            this["is_group"] = false;
        }
        if (!("is_im" in $$source)) {
            this["is_im"] = false;
        }
        if (!("is_mpim" in $$source)) {
            this["is_mpim"] = false;
        }
        if (!("is_private" in $$source)) {
            this["is_private"] = false;
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("is_archived" in $$source)) {
            this["is_archived"] = false;
        }
        if (!("updated" in $$source)) {
            this["updated"] = 0;
        }
        if (!("creator" in $$source)) {
            this["creator"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = {"value": "", "creator": "", "last_set": 0};
        }
        if (!("purpose" in $$source)) {
            this["purpose"] = {"value": "", "creator": "", "last_set": 0};
        }
        if (!("properties" in $$source)) {
            this["properties"] = {"tabs": [], "posting_restricted_to": null};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Channel instance from a string or object.
     */
    static createFrom($$source: any = {}): Channel {
        const $$createField13_0 = $$createType5;
        const $$createField14_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField13_0($$parsedSource["properties"]);
        }
        if ("previous_names" in $$parsedSource) {
            $$parsedSource["previous_names"] = $$createField14_0($$parsedSource["previous_names"]);
        }
        return new Channel($$parsedSource as Partial<Channel>);
    }
}

export class Im {
    "id": string;
    "created": number;
    "is_im": boolean;
    "is_archived": boolean;

    /**
     * the person you're dming
     */
    "user": string;
    "is_open": boolean;
    "properties": {"tabs"?: Tab[]};

    /** Creates a new Im instance. */
    constructor($$source: Partial<Im> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("is_im" in $$source)) {
            this["is_im"] = false;
        }
        if (!("is_archived" in $$source)) {
            this["is_archived"] = false;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("is_open" in $$source)) {
            this["is_open"] = false;
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Im instance from a string or object.
     */
    static createFrom($$source: any = {}): Im {
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField6_0($$parsedSource["properties"]);
        }
        return new Im($$parsedSource as Partial<Im>);
    }
}

export class Message {
    "user": string;
    "text": string;
    "ts": string;
    "type": string;
    "subtype"?: string;
    "team"?: string;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("ts" in $$source)) {
            this["ts"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class MessagesResponse {
    "messages": Message[];
    "has_more": boolean;
    "next_cursor": string;

    /** Creates a new MessagesResponse instance. */
    constructor($$source: Partial<MessagesResponse> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }
        if (!("next_cursor" in $$source)) {
            this["next_cursor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessagesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MessagesResponse {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new MessagesResponse($$parsedSource as Partial<MessagesResponse>);
    }
}

export class SlackSession {
    "d_cookie": string;
    "workspaces": { [_ in string]?: WorkspaceSession };

    /** Creates a new SlackSession instance. */
    constructor($$source: Partial<SlackSession> = {}) {
        if (!("d_cookie" in $$source)) {
            this["d_cookie"] = "";
        }
        if (!("workspaces" in $$source)) {
            this["workspaces"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlackSession instance from a string or object.
     */
    static createFrom($$source: any = {}): SlackSession {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workspaces" in $$parsedSource) {
            $$parsedSource["workspaces"] = $$createField1_0($$parsedSource["workspaces"]);
        }
        return new SlackSession($$parsedSource as Partial<SlackSession>);
    }
}

export class Tab {
    "type": string;
    "label": string;
    "id": string;
    "is_disabled": boolean | null;
    "data": {"file_id"?: string, "shared_ts"?: string, "mute_edit_updates"?: boolean, "folder_bookmark_id"?: string} | null;

    /** Creates a new Tab instance. */
    constructor($$source: Partial<Tab> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("is_disabled" in $$source)) {
            this["is_disabled"] = null;
        }
        if (!("data" in $$source)) {
            this["data"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tab instance from a string or object.
     */
    static createFrom($$source: any = {}): Tab {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tab($$parsedSource as Partial<Tab>);
    }
}

export class UserProfile {
    "id": string;
    "color": string;
    "is_bot": boolean;
    "profile": {"display_name": string, "real_name": string, "avatar_hash": string};

    /** Creates a new UserProfile instance. */
    constructor($$source: Partial<UserProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("is_bot" in $$source)) {
            this["is_bot"] = false;
        }
        if (!("profile" in $$source)) {
            this["profile"] = {"display_name": "", "real_name": "", "avatar_hash": ""};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): UserProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserProfile($$parsedSource as Partial<UserProfile>);
    }
}

export class WorkspaceSession {
    "token": string;
    "user_id": string;
    "team_name": string;
    "team_url": string;
    "team_icon": string;
    "enterprise_id"?: string;

    /** Creates a new WorkspaceSession instance. */
    constructor($$source: Partial<WorkspaceSession> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("team_name" in $$source)) {
            this["team_name"] = "";
        }
        if (!("team_url" in $$source)) {
            this["team_url"] = "";
        }
        if (!("team_icon" in $$source)) {
            this["team_icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceSession instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceSession($$parsedSource as Partial<WorkspaceSession>);
    }
}

// Private type creation functions
const $$createType0 = Tab.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Struct({
    "type": $$createType2,
    "user": $$createType2,
});
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Struct({
    "tabs": $$createType1,
    "posting_restricted_to": $$createType4,
});
const $$createType6 = $Create.Struct({
    "tabs": $$createType1,
});
const $$createType7 = Message.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = WorkspaceSession.createFrom;
const $$createType10 = $Create.Map($Create.Any, $$createType9);
